name: Build Openwrt Packages
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: /home/build/openwrt
jobs:
  build:
    strategy:
      matrix:
        platform:
          - target: mipsel_24kc
          - target: x86_64
          - target: aarch64_generic
        version:
          - openwrt-22.03
      fail-fast: true

    runs-on: ubuntu-latest
    container:
      image: docker://openwrtorg/sdk:${{matrix.platform.target}}-${{matrix.version}}
      env:
        TZ: Asia/Shanghai
      options: --user root
    steps:
      - name: create bin directory
        run: |
          mkdir ${GITHUB_WORKSPACE}/bin
          ln -s ${GITHUB_WORKSPACE}/bin /home/build/openwrt/bin
      - name: create config
        run: |
          wget -O .config https://raw.githubusercontent.com/tkit1994/mir3g-openwrt/main/config.default
          echo 'src-git-full tkit https://github.com/tkit1994/openwrt-packages.git' | tee -a feeds.conf.default
      - name: update feeds
        run: ./scripts/feeds update -a
      - name: install feed
        run: ./scripts/feeds install -a -f -p tkit
      - name: configure
        run: make defconfig
      - name: download
        run: make download -j$(nproc)
      - name: build
        run: make -j$(nproc) || make -j1 V=s
      - uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.version}}-${{matrix.platform.target}}
          path: bin/packages/${{matrix.platform.target}}/tkit
